package com.walphotodem.pmd.walphotoedem

/**
 */
const val MOCK_RESPONSE = "{\n" +
        "   \"data\":{\n" +
        "      \"album\":{\n" +
        "         \"__typename\":\"Album\",\n" +
        "         \"id\":\"dTRydwXhGQgthi1r2cKFmg\",\n" +
        "         \"name\":\"ANDROID minitest\",\n" +
        "         \"photos\":{\n" +
        "            \"__typename\":\"Photos\",\n" +
        "            \"count\":1,\n" +
        "            \"records\":[\n" +
        "               {\n" +
        "                  \"__typename\":\"Photo\",\n" +
        "                  \"urls\":[\n" +
        "                     {\n" +
        "                        \"__typename\":\"PhotoURLType\",\n" +
        "                        \"size_code\":\"small\",\n" +
        "                        \"url\":\"https://s3.amazonaws.com/waldo-thumbs-dev/small/5fb81262-1830-514f-bfad-8ecabb26b107.jpg\",\n" +
        "                        \"width\":64,\n" +
        "                        \"height\":95,\n" +
        "                        \"quality\":0.3,\n" +
        "                        \"mime\":\"image/jpeg\"\n" +
        "                     },\n" +
        "                     {\n" +
        "                        \"__typename\":\"PhotoURLType\",\n" +
        "                        \"size_code\":\"small2x\",\n" +
        "                        \"url\":\"https://s3.amazonaws.com/waldo-thumbs-dev/small2x/5fb81262-1830-514f-bfad-8ecabb26b107.jpg\",\n" +
        "                        \"width\":128,\n" +
        "                        \"height\":191,\n" +
        "                        \"quality\":0.3,\n" +
        "                        \"mime\":\"image/jpeg\"\n" +
        "                     },\n" +
        "                     {\n" +
        "                        \"__typename\":\"PhotoURLType\",\n" +
        "                        \"size_code\":\"medium\",\n" +
        "                        \"url\":\"https://s3.amazonaws.com/waldo-thumbs-dev/medium/5fb81262-1830-514f-bfad-8ecabb26b107.jpg\",\n" +
        "                        \"width\":256,\n" +
        "                        \"height\":381,\n" +
        "                        \"quality\":0.3,\n" +
        "                        \"mime\":\"image/jpeg\"\n" +
        "                     },\n" +
        "                     {\n" +
        "                        \"__typename\":\"PhotoURLType\",\n" +
        "                        \"size_code\":\"medium2x\",\n" +
        "                        \"url\":\"https://s3.amazonaws.com/waldo-thumbs-dev/medium2x/5fb81262-1830-514f-bfad-8ecabb26b107.jpg\",\n" +
        "                        \"width\":512,\n" +
        "                        \"height\":763,\n" +
        "                        \"quality\":0.6,\n" +
        "                        \"mime\":\"image/jpeg\"\n" +
        "                     },\n" +
        "                     {\n" +
        "                        \"__typename\":\"PhotoURLType\",\n" +
        "                        \"size_code\":\"large\",\n" +
        "                        \"url\":\"https://s3.amazonaws.com/waldo-thumbs-dev/large/5fb81262-1830-514f-bfad-8ecabb26b107.jpg\",\n" +
        "                        \"width\":588,\n" +
        "                        \"height\":876,\n" +
        "                        \"quality\":0.82,\n" +
        "                        \"mime\":\"image/jpeg\"\n" +
        "                     },\n" +
        "                     {\n" +
        "                        \"__typename\":\"PhotoURLType\",\n" +
        "                        \"size_code\":\"large1x\",\n" +
        "                        \"url\":\"https://s3.amazonaws.com/waldo-thumbs-dev/large1x/5fb81262-1830-514f-bfad-8ecabb26b107.jpg\",\n" +
        "                        \"width\":588,\n" +
        "                        \"height\":876,\n" +
        "                        \"quality\":0.82,\n" +
        "                        \"mime\":\"image/jpeg\"\n" +
        "                     },\n" +
        "                     {\n" +
        "                        \"__typename\":\"PhotoURLType\",\n" +
        "                        \"size_code\":\"large2x\",\n" +
        "                        \"url\":\"https://s3.amazonaws.com/waldo-thumbs-dev/large2x/5fb81262-1830-514f-bfad-8ecabb26b107.jpg\",\n" +
        "                        \"width\":588,\n" +
        "                        \"height\":876,\n" +
        "                        \"quality\":0.82,\n" +
        "                        \"mime\":\"image/jpeg\"\n" +
        "                     }\n" +
        "                  ]\n" +
        "               }\n" +
        "            ]\n" +
        "         }\n" +
        "      }\n" +
        "   },\n" +
        "   \"extensions\":{\n" +
        "      \"completedMs\":15\n" +
        "   }\n" +
        "}"